### ISSUE TITLE
Plugin don't work 

### ISSUE THREAD

**Issue by pawelkowalczyk98** [ConsenSys/mythril-example-plugin#1]
ubuntu@root:~$ myth
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/myth", line 5, in <module>
    from mythril.interfaces.cli import main
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mythril/interfaces/cli.py", line 39, in <module>
    _ = MythrilPluginLoader()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mythril/support/support_utils.py", line 25, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mythril/plugin/loader.py", line 32, in __init__
    self._load_default_enabled()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mythril/plugin/loader.py", line 76, in _load_default_enabled
    for plugin_name in PluginDiscovery().get_plugins(default_enabled=True):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mythril/plugin/discovery.py", line 56, in get_plugins
    for plugin_name, plugin_class in self.installed_plugins.items()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mythril/plugin/discovery.py", line 26, in installed_plugins
    self.init_installed_plugins()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mythril/plugin/discovery.py", line 18, in init_installed_plugins
    self._installed_plugins = {
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mythril/plugin/discovery.py", line 19, in <dictcomp>
    entry_point.name: entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/myth_example_detector-0.0.1-py3.8.egg/myth_example_detector/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/myth_example_detector-0.0.1-py3.8.egg/myth_example_detector/detector.py", line 21, in <module>
NameError: name 'MythrilPlugin' is not defined

Ubuntu 20.04.1 LTS  64-bit
python 3.8
mythril 0.22.9 but on other versions, similar error

**Comment by pawelkowalczyk98** [comment]
Fixed
